---
title: "딸기 프로젝트"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#------------------ Packages ------------------
library(devtools)
#깃허브에서 딸기 데이터셋 가져오기
devtools::install_github("docuhut/datalink", force=TRUE)
library(strawberry)
library(ggplot2)
#------------------ Data ------------------
#데이터셋 StrawBerry 사용 준비하기
data(StrawBerry)

#품종별 데이터 분리
data <- split(StrawBerry, StrawBerry$date)
data1 <- data$'12월 25일'
data2 <- data$'1월 25일'
data3 <- data$'2월 25일'
data4 <- data$'3월 25일'
data5 <- data$'4월 25일'

library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### 겨울철(12월 25일) 당도 히스토그램

```{r}
ggplot(data1, aes(x=data1$brix, fill=data1$type, color=data1$type),)+geom_histogram(binwidth=0.1)+labs(x="겨울철(12월 25일) 당도 히스토그램", fill = "종류", color="종류")+scale_color_manual(values=c("#E9292C", "#1d4785"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### 겨울철(1월 25일) 당도 히스토그램

```{r}
ggplot(data2, aes(x=data2$brix, fill=data2$type, color=data2$type),)+geom_histogram(binwidth=0.1)+labs(x="겨울철(1월 25일) 당도 히스토그램", fill = "종류", color="종류")+scale_color_manual(values=c("#E9292C", "#1d4785"))
```

### 겨울철(1월 25일) 당도 히스토그램

```{r}
ggplot(data3, aes(x=data3$brix, fill=data3$type, color=data3$type),)+geom_histogram(binwidth=0.1)+labs(x="겨울철(2월 25일) 당도 히스토그램", fill = "종류", color="종류")+scale_color_manual(values=c("#E9292C", "#1d4785"))
```

